/**
 *
 *  SubscribeMap.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "SubscribeMap.h"
#include "Device.h"
#include "Topic.h"
#include "User.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::iot_server;

const std::string SubscribeMap::Cols::_map_id = "map_id";
const std::string SubscribeMap::Cols::_target_user_id = "target_user_id";
const std::string SubscribeMap::Cols::_target_device_id = "target_device_id";
const std::string SubscribeMap::Cols::_target_topic_id = "target_topic_id";
const std::string SubscribeMap::primaryKeyName = "map_id";
const bool SubscribeMap::hasPrimaryKey = true;
const std::string SubscribeMap::tableName = "subscribe_map";

const std::vector<typename SubscribeMap::MetaData> SubscribeMap::metaData_={
{"map_id","uint32_t","int unsigned",4,1,1,1},
{"target_user_id","uint32_t","int unsigned",4,0,0,1},
{"target_device_id","uint32_t","int unsigned",4,0,0,1},
{"target_topic_id","uint32_t","int unsigned",4,0,0,0}
};
const std::string &SubscribeMap::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
SubscribeMap::SubscribeMap(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["map_id"].isNull())
        {
            mapId_=std::make_shared<uint32_t>(r["map_id"].as<uint32_t>());
        }
        if(!r["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>(r["target_user_id"].as<uint32_t>());
        }
        if(!r["target_device_id"].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>(r["target_device_id"].as<uint32_t>());
        }
        if(!r["target_topic_id"].isNull())
        {
            targetTopicId_=std::make_shared<uint32_t>(r["target_topic_id"].as<uint32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            mapId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            targetTopicId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
    }

}

SubscribeMap::SubscribeMap(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            mapId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            targetTopicId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
}

SubscribeMap::SubscribeMap(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("map_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["map_id"].isNull())
        {
            mapId_=std::make_shared<uint32_t>((uint32_t)pJson["map_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson["target_user_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_device_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["target_device_id"].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson["target_device_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_topic_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["target_topic_id"].isNull())
        {
            targetTopicId_=std::make_shared<uint32_t>((uint32_t)pJson["target_topic_id"].asUInt64());
        }
    }
}

void SubscribeMap::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            mapId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            targetTopicId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
}

void SubscribeMap::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("map_id"))
    {
        if(!pJson["map_id"].isNull())
        {
            mapId_=std::make_shared<uint32_t>((uint32_t)pJson["map_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson["target_user_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_device_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["target_device_id"].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson["target_device_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_topic_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["target_topic_id"].isNull())
        {
            targetTopicId_=std::make_shared<uint32_t>((uint32_t)pJson["target_topic_id"].asUInt64());
        }
    }
}

const uint32_t &SubscribeMap::getValueOfMapId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(mapId_)
        return *mapId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &SubscribeMap::getMapId() const noexcept
{
    return mapId_;
}
void SubscribeMap::setMapId(const uint32_t &pMapId) noexcept
{
    mapId_ = std::make_shared<uint32_t>(pMapId);
    dirtyFlag_[0] = true;
}
const typename SubscribeMap::PrimaryKeyType & SubscribeMap::getPrimaryKey() const
{
    assert(mapId_);
    return *mapId_;
}

const uint32_t &SubscribeMap::getValueOfTargetUserId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(targetUserId_)
        return *targetUserId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &SubscribeMap::getTargetUserId() const noexcept
{
    return targetUserId_;
}
void SubscribeMap::setTargetUserId(const uint32_t &pTargetUserId) noexcept
{
    targetUserId_ = std::make_shared<uint32_t>(pTargetUserId);
    dirtyFlag_[1] = true;
}

const uint32_t &SubscribeMap::getValueOfTargetDeviceId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(targetDeviceId_)
        return *targetDeviceId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &SubscribeMap::getTargetDeviceId() const noexcept
{
    return targetDeviceId_;
}
void SubscribeMap::setTargetDeviceId(const uint32_t &pTargetDeviceId) noexcept
{
    targetDeviceId_ = std::make_shared<uint32_t>(pTargetDeviceId);
    dirtyFlag_[2] = true;
}

const uint32_t &SubscribeMap::getValueOfTargetTopicId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(targetTopicId_)
        return *targetTopicId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &SubscribeMap::getTargetTopicId() const noexcept
{
    return targetTopicId_;
}
void SubscribeMap::setTargetTopicId(const uint32_t &pTargetTopicId) noexcept
{
    targetTopicId_ = std::make_shared<uint32_t>(pTargetTopicId);
    dirtyFlag_[3] = true;
}
void SubscribeMap::setTargetTopicIdToNull() noexcept
{
    targetTopicId_.reset();
    dirtyFlag_[3] = true;
}

void SubscribeMap::updateId(const uint64_t id)
{
    mapId_ = std::make_shared<uint32_t>(static_cast<uint32_t>(id));
}

const std::vector<std::string> &SubscribeMap::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "target_user_id",
        "target_device_id",
        "target_topic_id"
    };
    return inCols;
}

void SubscribeMap::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTargetUserId())
        {
            binder << getValueOfTargetUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTargetDeviceId())
        {
            binder << getValueOfTargetDeviceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTargetTopicId())
        {
            binder << getValueOfTargetTopicId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> SubscribeMap::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void SubscribeMap::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTargetUserId())
        {
            binder << getValueOfTargetUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTargetDeviceId())
        {
            binder << getValueOfTargetDeviceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getTargetTopicId())
        {
            binder << getValueOfTargetTopicId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value SubscribeMap::toJson() const
{
    Json::Value ret;
    if(getMapId())
    {
        ret["map_id"]=getValueOfMapId();
    }
    else
    {
        ret["map_id"]=Json::Value();
    }
    if(getTargetUserId())
    {
        ret["target_user_id"]=getValueOfTargetUserId();
    }
    else
    {
        ret["target_user_id"]=Json::Value();
    }
    if(getTargetDeviceId())
    {
        ret["target_device_id"]=getValueOfTargetDeviceId();
    }
    else
    {
        ret["target_device_id"]=Json::Value();
    }
    if(getTargetTopicId())
    {
        ret["target_topic_id"]=getValueOfTargetTopicId();
    }
    else
    {
        ret["target_topic_id"]=Json::Value();
    }
    return ret;
}

Json::Value SubscribeMap::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getMapId())
            {
                ret[pMasqueradingVector[0]]=getValueOfMapId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTargetUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTargetUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTargetDeviceId())
            {
                ret[pMasqueradingVector[2]]=getValueOfTargetDeviceId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getTargetTopicId())
            {
                ret[pMasqueradingVector[3]]=getValueOfTargetTopicId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getMapId())
    {
        ret["map_id"]=getValueOfMapId();
    }
    else
    {
        ret["map_id"]=Json::Value();
    }
    if(getTargetUserId())
    {
        ret["target_user_id"]=getValueOfTargetUserId();
    }
    else
    {
        ret["target_user_id"]=Json::Value();
    }
    if(getTargetDeviceId())
    {
        ret["target_device_id"]=getValueOfTargetDeviceId();
    }
    else
    {
        ret["target_device_id"]=Json::Value();
    }
    if(getTargetTopicId())
    {
        ret["target_topic_id"]=getValueOfTargetTopicId();
    }
    else
    {
        ret["target_topic_id"]=Json::Value();
    }
    return ret;
}

bool SubscribeMap::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("map_id"))
    {
        if(!validJsonOfField(0, "map_id", pJson["map_id"], err, true))
            return false;
    }
    if(pJson.isMember("target_user_id"))
    {
        if(!validJsonOfField(1, "target_user_id", pJson["target_user_id"], err, true))
            return false;
    }
    else
    {
        err="The target_user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("target_device_id"))
    {
        if(!validJsonOfField(2, "target_device_id", pJson["target_device_id"], err, true))
            return false;
    }
    else
    {
        err="The target_device_id column cannot be null";
        return false;
    }
    if(pJson.isMember("target_topic_id"))
    {
        if(!validJsonOfField(3, "target_topic_id", pJson["target_topic_id"], err, true))
            return false;
    }
    return true;
}
bool SubscribeMap::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SubscribeMap::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("map_id"))
    {
        if(!validJsonOfField(0, "map_id", pJson["map_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("target_user_id"))
    {
        if(!validJsonOfField(1, "target_user_id", pJson["target_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("target_device_id"))
    {
        if(!validJsonOfField(2, "target_device_id", pJson["target_device_id"], err, false))
            return false;
    }
    if(pJson.isMember("target_topic_id"))
    {
        if(!validJsonOfField(3, "target_topic_id", pJson["target_topic_id"], err, false))
            return false;
    }
    return true;
}
bool SubscribeMap::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool SubscribeMap::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
User SubscribeMap::getUser(const DbClientPtr &clientPtr) const {
    const static std::string sql = "select * from user where user_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *targetUserId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return User(r[0]);
}

void SubscribeMap::getUser(const DbClientPtr &clientPtr,
                           const std::function<void(User)> &rcb,
                           const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from user where user_id = ?";
    *clientPtr << sql
               << *targetUserId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(User(r[0]));
                    }
               }
               >> ecb;
}
Device SubscribeMap::getDevice(const DbClientPtr &clientPtr) const {
    const static std::string sql = "select * from device where device_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *targetDeviceId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Device(r[0]);
}

void SubscribeMap::getDevice(const DbClientPtr &clientPtr,
                             const std::function<void(Device)> &rcb,
                             const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from device where device_id = ?";
    *clientPtr << sql
               << *targetDeviceId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Device(r[0]));
                    }
               }
               >> ecb;
}
Topic SubscribeMap::getTopic(const DbClientPtr &clientPtr) const {
    const static std::string sql = "select * from topic where topic_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *targetTopicId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Topic(r[0]);
}

void SubscribeMap::getTopic(const DbClientPtr &clientPtr,
                            const std::function<void(Topic)> &rcb,
                            const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from topic where topic_id = ?";
    *clientPtr << sql
               << *targetTopicId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Topic(r[0]));
                    }
               }
               >> ecb;
}
