version: '3'

services:
  iotserver:
    build:
      context: arch
      dockerfile: Dockerfile
    container_name: iotserver
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8089:8089"
    restart: always
  mysql:
#    build:
#      context: mysql
#      dockerfile: Dockerfile
    image: mysql:8.2.0
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: iot_server
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: server
      MYSQL_PASSWORD: y2A@kw9&
    container_name: mysql-compose
    restart: always
    volumes:
      #- "./mysql/db/:/var/lib/mysql"
      - "./mysql/sql/:/docker-entrypoint-initdb.d"
    command: --default-authentication-plugin=caching_sha2_password

  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "6379:6379"
    container_name: redis-compose
    restart: always
    volumes:
      - "./redis/db/:/data"

  mosquitto:
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: mosquitto
      dockerfile: Dockerfile
#    image: eclipse-mosquitto:latest
    restart: always
    container_name: mosquitto-compose
    ports:
      - "1883:1883"
      - "9001:9001"

  qsign:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: hansaes/unidbg-fetch-qsign:latest
    ports:
      - "9888:8080"
#    environment:
#      ANDROID_ID: 899d93e65c486d2
    restart: always
    container_name: sign-compose

  cqhttp:
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: cqhttp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9889:8080"
    volumes:
      - "./cqhttp/cqconf:/data"
