## PASS 20240116
# New Device
PUT http://localhost:8089/device/new
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370
Content-Type: application/json

{
  "device_sn": "ioawnmd102",
  "device_name": "test device",
  "device_comment": "Test comment",
  "target_permission_level": 50
}

###

## PASS 20240116
# Get All Device
GET http://localhost:8089/device/all
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370

###

## PASS 20240116
# Delete Device
DELETE http://localhost:8089/device/delete
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370
Content-Type: application/json

{
  "device_id": 2
}
