## PASS 20240116
# New Device
PUT http://localhost:8089/api/device/new
Authorization: f0601362-b247-4313-a255-feffa65b5e41
Content-Type: application/json

{
  "device_sn": "DTESTSNDATA",
  "device_name": "TD",
  "device_comment": "Test comment",
  "target_permission_level": 1
}

###

## PASS 20240116
# Get All Device
GET http://localhost:8089/api/device/all
Authorization: f0601362-b247-4313-a255-feffa65b5e41

###

## PASS 20240116
# Get Target Device
GET http://localhost:8089/api/device/info
Authorization: f0601362-b247-4313-a255-feffa65b5e41
Content-Type: application/json

{
  "device_sn": "DTESTSNDATA"
}

###

## PASS 20240116
# Delete Device
DELETE http://localhost:8089/api/device/delete
Authorization: f0601362-b247-4313-a255-feffa65b5e41
Content-Type: application/json

{
  "device_sn": 2
}
