# PASS 20240116
# add device
PUT http://localhost:8089/user/device/add
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370
Content-Type: application/json

{
  "device_id": 4
}

###

# PASS 20240116
# Get All Subscribed device
GET http://localhost:8089/user/device/getAll
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370

###

# TODO Retest when full topic ok
# Get target device topic info
GET http://localhost:8089/user/device/get
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370
Content-Type: application/json

{
  "device_id": 3
}

###


# PASS 20240116
# remove device from user sub
DELETE http://localhost:8089/user/device/remove
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370
Content-Type: application/json

{
  "device_id": 4
}

###
