# PASS 20240116
# add device
PUT http://localhost:8089/api/subscribe/new
Authorization: b151d87c-b6b9-4337-9d9f-fbc231a87a7a
Content-Type: application/json

{
  "device_sn": "TESESNDDT",
  "topic": "TestTopic"
}

###

# PASS 20240116
# Get All Subscribed device
GET http://localhost:8089/api/subscribe/all
Authorization: b151d87c-b6b9-4337-9d9f-fbc231a87a7a

###

# PASS 20240116
# remove device from user sub
DELETE http://localhost:8089/api/subscribe/delete
Authorization: b151d87c-b6b9-4337-9d9f-fbc231a87a7a
Content-Type: application/json

{
  "device_sn": "TESESNDDT",
  "topic": "TestTopic"
}

###
