# PASS 20240113
# register
PUT http://localhost:8089/api/user/register
Content-Type: application/json

{
  "user_name": "testUser10",
  "user_password": "pwd10"
}

###


# PASS 20240114
# login
POST http://localhost:8089/api/user/login
Content-Type: application/json

{
  "key": "testUser10",
  "pwd": "pwd10"
}

###

# PASS 20240114
# getInfo
GET http://localhost:8089/api/user/info
Authorization: fd3d18ae-9174-4900-85dc-906a4d003c21

###

# PASS 20240114
# logout
DELETE http://localhost:8089/api/user/logout
Authorization: fd3d18ae-9174-4900-85dc-906a4d003c21

###