# PASS 20240113
# register
PUT http://localhost:8089/user/register
Content-Type: application/json

{
  "user_name": "testUser10",
  "user_password": "pwd10",
  "user_permission_id": 0
}

###


# PASS 20240114
# login
POST http://localhost:8089/user/login
Content-Type: application/json

{
  "key": "admin",
  "pwd": "admin"
}

###

# PASS 20240114
# getInfo
GET http://localhost:8089/user/info
Authorization: 3a9c2557-1202-4587-9366-aa13ffa3f370

###

# PASS 20240114
# logout
DELETE http://localhost:8089/user/logout
Authorization: a1c3ad95-3012-4e94-aaf9-9b52d76f2449

###