//
// Created by diam on 24-1-20.
//

#ifndef IOTSERVER_CQWEBSOCKETPRIVATECHATMESSAGEFILTER_H
#define IOTSERVER_CQWEBSOCKETPRIVATECHATMESSAGEFILTER_H



class CqWebSocketPrivateChatMessageFilter {

};



#endif //IOTSERVER_CQWEBSOCKETPRIVATECHATMESSAGEFILTER_H
