/**
 *
 *  UserDeviceAliasMap.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UserDeviceAliasMap.h"
#include "Device.h"
#include "User.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::iot_server;

const std::string UserDeviceAliasMap::Cols::_alias_map_id = "alias_map_id";
const std::string UserDeviceAliasMap::Cols::_target_user_id = "target_user_id";
const std::string UserDeviceAliasMap::Cols::_target_device_id = "target_device_id";
const std::string UserDeviceAliasMap::Cols::_alias_name = "alias_name";
const std::string UserDeviceAliasMap::primaryKeyName = "alias_map_id";
const bool UserDeviceAliasMap::hasPrimaryKey = true;
const std::string UserDeviceAliasMap::tableName = "user_device_alias_map";

const std::vector<typename UserDeviceAliasMap::MetaData> UserDeviceAliasMap::metaData_={
{"alias_map_id","uint32_t","int unsigned",4,1,1,1},
{"target_user_id","uint32_t","int unsigned",4,0,0,1},
{"target_device_id","uint32_t","int unsigned",4,0,0,1},
{"alias_name","std::string","varchar(255)",255,0,0,1}
};
const std::string &UserDeviceAliasMap::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserDeviceAliasMap::UserDeviceAliasMap(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["alias_map_id"].isNull())
        {
            aliasMapId_=std::make_shared<uint32_t>(r["alias_map_id"].as<uint32_t>());
        }
        if(!r["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>(r["target_user_id"].as<uint32_t>());
        }
        if(!r["target_device_id"].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>(r["target_device_id"].as<uint32_t>());
        }
        if(!r["alias_name"].isNull())
        {
            aliasName_=std::make_shared<std::string>(r["alias_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            aliasMapId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>(r[index].as<uint32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            aliasName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

UserDeviceAliasMap::UserDeviceAliasMap(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            aliasMapId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            aliasName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

UserDeviceAliasMap::UserDeviceAliasMap(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("alias_map_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["alias_map_id"].isNull())
        {
            aliasMapId_=std::make_shared<uint32_t>((uint32_t)pJson["alias_map_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson["target_user_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_device_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["target_device_id"].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson["target_device_id"].asUInt64());
        }
    }
    if(pJson.isMember("alias_name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["alias_name"].isNull())
        {
            aliasName_=std::make_shared<std::string>(pJson["alias_name"].asString());
        }
    }
}

void UserDeviceAliasMap::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            aliasMapId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            aliasName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void UserDeviceAliasMap::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("alias_map_id"))
    {
        if(!pJson["alias_map_id"].isNull())
        {
            aliasMapId_=std::make_shared<uint32_t>((uint32_t)pJson["alias_map_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["target_user_id"].isNull())
        {
            targetUserId_=std::make_shared<uint32_t>((uint32_t)pJson["target_user_id"].asUInt64());
        }
    }
    if(pJson.isMember("target_device_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["target_device_id"].isNull())
        {
            targetDeviceId_=std::make_shared<uint32_t>((uint32_t)pJson["target_device_id"].asUInt64());
        }
    }
    if(pJson.isMember("alias_name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["alias_name"].isNull())
        {
            aliasName_=std::make_shared<std::string>(pJson["alias_name"].asString());
        }
    }
}

const uint32_t &UserDeviceAliasMap::getValueOfAliasMapId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(aliasMapId_)
        return *aliasMapId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &UserDeviceAliasMap::getAliasMapId() const noexcept
{
    return aliasMapId_;
}
void UserDeviceAliasMap::setAliasMapId(const uint32_t &pAliasMapId) noexcept
{
    aliasMapId_ = std::make_shared<uint32_t>(pAliasMapId);
    dirtyFlag_[0] = true;
}
const typename UserDeviceAliasMap::PrimaryKeyType & UserDeviceAliasMap::getPrimaryKey() const
{
    assert(aliasMapId_);
    return *aliasMapId_;
}

const uint32_t &UserDeviceAliasMap::getValueOfTargetUserId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(targetUserId_)
        return *targetUserId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &UserDeviceAliasMap::getTargetUserId() const noexcept
{
    return targetUserId_;
}
void UserDeviceAliasMap::setTargetUserId(const uint32_t &pTargetUserId) noexcept
{
    targetUserId_ = std::make_shared<uint32_t>(pTargetUserId);
    dirtyFlag_[1] = true;
}

const uint32_t &UserDeviceAliasMap::getValueOfTargetDeviceId() const noexcept
{
    const static uint32_t defaultValue = uint32_t();
    if(targetDeviceId_)
        return *targetDeviceId_;
    return defaultValue;
}
const std::shared_ptr<uint32_t> &UserDeviceAliasMap::getTargetDeviceId() const noexcept
{
    return targetDeviceId_;
}
void UserDeviceAliasMap::setTargetDeviceId(const uint32_t &pTargetDeviceId) noexcept
{
    targetDeviceId_ = std::make_shared<uint32_t>(pTargetDeviceId);
    dirtyFlag_[2] = true;
}

const std::string &UserDeviceAliasMap::getValueOfAliasName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(aliasName_)
        return *aliasName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserDeviceAliasMap::getAliasName() const noexcept
{
    return aliasName_;
}
void UserDeviceAliasMap::setAliasName(const std::string &pAliasName) noexcept
{
    aliasName_ = std::make_shared<std::string>(pAliasName);
    dirtyFlag_[3] = true;
}
void UserDeviceAliasMap::setAliasName(std::string &&pAliasName) noexcept
{
    aliasName_ = std::make_shared<std::string>(std::move(pAliasName));
    dirtyFlag_[3] = true;
}

void UserDeviceAliasMap::updateId(const uint64_t id)
{
    aliasMapId_ = std::make_shared<uint32_t>(static_cast<uint32_t>(id));
}

const std::vector<std::string> &UserDeviceAliasMap::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "target_user_id",
        "target_device_id",
        "alias_name"
    };
    return inCols;
}

void UserDeviceAliasMap::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTargetUserId())
        {
            binder << getValueOfTargetUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTargetDeviceId())
        {
            binder << getValueOfTargetDeviceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAliasName())
        {
            binder << getValueOfAliasName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserDeviceAliasMap::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void UserDeviceAliasMap::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTargetUserId())
        {
            binder << getValueOfTargetUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTargetDeviceId())
        {
            binder << getValueOfTargetDeviceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAliasName())
        {
            binder << getValueOfAliasName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserDeviceAliasMap::toJson() const
{
    Json::Value ret;
    if(getAliasMapId())
    {
        ret["alias_map_id"]=getValueOfAliasMapId();
    }
    else
    {
        ret["alias_map_id"]=Json::Value();
    }
    if(getTargetUserId())
    {
        ret["target_user_id"]=getValueOfTargetUserId();
    }
    else
    {
        ret["target_user_id"]=Json::Value();
    }
    if(getTargetDeviceId())
    {
        ret["target_device_id"]=getValueOfTargetDeviceId();
    }
    else
    {
        ret["target_device_id"]=Json::Value();
    }
    if(getAliasName())
    {
        ret["alias_name"]=getValueOfAliasName();
    }
    else
    {
        ret["alias_name"]=Json::Value();
    }
    return ret;
}

Json::Value UserDeviceAliasMap::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getAliasMapId())
            {
                ret[pMasqueradingVector[0]]=getValueOfAliasMapId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTargetUserId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTargetUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTargetDeviceId())
            {
                ret[pMasqueradingVector[2]]=getValueOfTargetDeviceId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getAliasName())
            {
                ret[pMasqueradingVector[3]]=getValueOfAliasName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getAliasMapId())
    {
        ret["alias_map_id"]=getValueOfAliasMapId();
    }
    else
    {
        ret["alias_map_id"]=Json::Value();
    }
    if(getTargetUserId())
    {
        ret["target_user_id"]=getValueOfTargetUserId();
    }
    else
    {
        ret["target_user_id"]=Json::Value();
    }
    if(getTargetDeviceId())
    {
        ret["target_device_id"]=getValueOfTargetDeviceId();
    }
    else
    {
        ret["target_device_id"]=Json::Value();
    }
    if(getAliasName())
    {
        ret["alias_name"]=getValueOfAliasName();
    }
    else
    {
        ret["alias_name"]=Json::Value();
    }
    return ret;
}

bool UserDeviceAliasMap::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("alias_map_id"))
    {
        if(!validJsonOfField(0, "alias_map_id", pJson["alias_map_id"], err, true))
            return false;
    }
    if(pJson.isMember("target_user_id"))
    {
        if(!validJsonOfField(1, "target_user_id", pJson["target_user_id"], err, true))
            return false;
    }
    else
    {
        err="The target_user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("target_device_id"))
    {
        if(!validJsonOfField(2, "target_device_id", pJson["target_device_id"], err, true))
            return false;
    }
    else
    {
        err="The target_device_id column cannot be null";
        return false;
    }
    if(pJson.isMember("alias_name"))
    {
        if(!validJsonOfField(3, "alias_name", pJson["alias_name"], err, true))
            return false;
    }
    else
    {
        err="The alias_name column cannot be null";
        return false;
    }
    return true;
}
bool UserDeviceAliasMap::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserDeviceAliasMap::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("alias_map_id"))
    {
        if(!validJsonOfField(0, "alias_map_id", pJson["alias_map_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("target_user_id"))
    {
        if(!validJsonOfField(1, "target_user_id", pJson["target_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("target_device_id"))
    {
        if(!validJsonOfField(2, "target_device_id", pJson["target_device_id"], err, false))
            return false;
    }
    if(pJson.isMember("alias_name"))
    {
        if(!validJsonOfField(3, "alias_name", pJson["alias_name"], err, false))
            return false;
    }
    return true;
}
bool UserDeviceAliasMap::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserDeviceAliasMap::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
User UserDeviceAliasMap::getUser(const DbClientPtr &clientPtr) const {
    const static std::string sql = "select * from user where user_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *targetUserId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return User(r[0]);
}

void UserDeviceAliasMap::getUser(const DbClientPtr &clientPtr,
                                 const std::function<void(User)> &rcb,
                                 const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from user where user_id = ?";
    *clientPtr << sql
               << *targetUserId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(User(r[0]));
                    }
               }
               >> ecb;
}
Device UserDeviceAliasMap::getDevice(const DbClientPtr &clientPtr) const {
    const static std::string sql = "select * from device where device_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *targetDeviceId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Device(r[0]);
}

void UserDeviceAliasMap::getDevice(const DbClientPtr &clientPtr,
                                   const std::function<void(Device)> &rcb,
                                   const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from device where device_id = ?";
    *clientPtr << sql
               << *targetDeviceId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Device(r[0]));
                    }
               }
               >> ecb;
}
